//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTVNTuan2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="tac gia khong duoc de trong")]
        [StringLength(30,ErrorMessage ="tac gia khong duoc qua 30 ki tu")]
        public string Arthor { get; set; }
        [Required(ErrorMessage = "ten sach khong duoc de trong")]
        [StringLength(30, ErrorMessage = "ten sach khong duoc qua 100 ki tu")]
        public string Title { get; set; }
        public string Description { get; set; }
        public string ImageCover { get; set; }
        [Range(1000,10000000,ErrorMessage ="Gia tu 1K den 1M")]
        public Nullable<double> Price { get; set; }
    }
}
